sudo: false

language: objective-c
os: osx
osx_image: xcode9.1

env:
  - TARGET_PLATFORM=android
  - TARGET_PLATFORM=ios

cache:
  directories:
    - node_modules

before_install:
- export LANG=en_US.UTF-8

install:
- npm install
- if [ $TARGET_PLATFORM = "android" ]; then
    brew update &&
    brew install gradle &&
    scripts/setup-android-sdk.sh &&
    export ANDROID_HOME=$(pwd)/android-sdk-macosx &&
    export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2;
  fi

script:
- npm run testjs

after_success:

deploy:
